//! Tiny Polish G2P without Python.
//!
//! ```no_run
//! let g2p = tiny_g2p::G2P::embedded(tiny_g2p::Mode::Float).unwrap();
//! assert_eq!(g2p.phonemize_str("Szczebrzeszyn"), "ʂ tʂ ɛ b ʐ ɛ ʂ ɨ n̪");
//!
//! // Several words at once: whitespace splits, one transcription per line.
//! let batch = g2p.phonemize_text("Wrocław morze może");
//! assert_eq!(batch.lines().count(), 3);
//! ```
//!
//! The whole model is 142 KiB of embedded weights, a 33-character window and
//! arithmetic -- so the same core serves the CLI (`tiny-g2p`), the browser
//! (`tiny-g2p-wasm`) and anything that can call into Rust.
//!
//! **Inference is infallible.** Every function here takes any string of any
//! length, in any Unicode state, and returns phones: the only failure mode in
//! the crate is a corrupt weights blob, which is checked once at
//! construction. The window is a *training* fact, not an input limit -- see
//! [`Blob::window_len`] -- and nothing refuses input because of it.
//!
//! # What is public, and why
//!
//! Deliberately small: [`G2P`], [`Mode`], [`Blob`], [`BlobError`],
//! [`EMBEDDED_WEIGHTS`], and the [`gold`] scorer the CLI's `eval` uses. The
//! inference internals -- the forward pass, the text encoder, the nasal-split
//! tables, the canonicalisation -- are `pub(crate)`, because everything
//! `pub` here is a compatibility promise this crate would have to keep.

#![warn(missing_docs)]

pub mod blob;
pub mod gold;
pub(crate) mod canon;
pub(crate) mod exceptions;
pub(crate) mod model;
pub(crate) mod phones;
pub(crate) mod text;

pub use blob::{Blob, BlobError};
pub use exceptions::parse_dictionary;
pub use model::Mode;

/// The weights the binary carries, generated by `tiny-g2p export`.
pub const EMBEDDED_WEIGHTS: &[u8] = include_bytes!("../weights/tiny_g2p.bin");

/// A loaded model plus everything around it: vocabularies, the nasal-split
/// tables, and the exception path.
pub struct G2P {
    blob: Blob,
    mode: Mode,
    exceptions: exceptions::Exceptions,
}

impl G2P {
    /// Parse a blob in memory.
    pub fn from_bytes(data: &[u8], mode: Mode) -> Result<G2P, blob::BlobError> {
        let blob = Blob::parse(data)?;
        let exceptions = exceptions::Exceptions::new(&blob);
        Ok(G2P { blob, mode, exceptions })
    }

    /// The weights compiled into this build.
    pub fn embedded(mode: Mode) -> Result<G2P, blob::BlobError> {
        G2P::from_bytes(EMBEDDED_WEIGHTS, mode)
    }

    /// The parsed weights and tables this model runs on.
    pub fn blob(&self) -> &Blob {
        &self.blob
    }

    /// The arithmetic the model was built with, [`Mode::Float`] or
    /// [`Mode::Int8`].
    pub fn mode(&self) -> Mode {
        self.mode
    }

    /// Add words to the exception path from a `word<TAB>phones` dictionary.
    ///
    /// The reliable route for borrowings and names the model cannot spell from
    /// its own rules. Takes the dictionary's *text*, not a path: this crate
    /// does no I/O and takes no dependency to do it, so the caller decides
    /// where the file comes from.
    ///
    /// Additions are additive and override the model for the words they name.
    /// They also outrank everything else, including a [suggested
    /// reading](G2P::load_suggestions) and the embedded acronym table: a
    /// dictionary someone wrote is an assertion, and an assertion is not
    /// weighed against evidence.
    pub fn load_lexicon(&mut self, text: &str) {
        self.exceptions.load_lexicon(text);
    }

    /// Add readings the caller *suggests* rather than asserts.
    ///
    /// Identical in format to [`G2P::load_lexicon`] and weaker in authority: a
    /// suggestion answers for a word only where nothing asserted, and no
    /// curated acronym entry, has an answer. This is what `tinyg2p
    /// miss-lexicon` writes — a lexicon's readings for the words a model
    /// disagrees with. That is good evidence; it is not the same as a person
    /// saying "this is my name".
    ///
    /// `G2P::explain` distinguishes the two, reporting `dictionary` for an
    /// assertion and `suggestion` for one of these.
    pub fn load_suggestions(&mut self, text: &str) {
        self.exceptions.load_suggestions(text);
    }

    /// The character window the taps cover (33). Words longer than this
    /// transcribe like any other -- the model is extrapolating, which is the
    /// caller's judgement to make, not this crate's.
    pub fn window_len(&self) -> usize {
        self.blob.window_len()
    }

    /// Whether `word` fits the training window.
    pub fn in_window(&self, word: &str) -> bool {
        text::normalize(word).chars().count() <= self.window_len()
    }

    /// Transcribe one word: normalise, try the exception path, otherwise run
    /// the model, then split merged nasals back to MFA's oral+nasal form.
    pub fn phonemize(&self, word: &str) -> Vec<String> {
        let normalized = text::normalize(word);
        if let Some(reading) = self.exceptions.lookup(&normalized) {
            return reading;
        }
        self.model_only(&normalized)
    }

    /// The model's own answer, with the exception path switched off.
    pub fn phonemize_model_only(&self, word: &str) -> Vec<String> {
        self.model_only(&text::normalize(word))
    }

    fn model_only(&self, normalized: &str) -> Vec<String> {
        if normalized.is_empty() {
            return Vec::new();
        }
        let chars: Vec<char> = normalized.chars().collect();
        let ids = text::Encoder::new(&self.blob).encode(normalized);
        let labels = text::decode(
            &self.blob,
            &model::Model::new(&self.blob, self.mode).argmax(&ids),
        );
        phones::restore(&self.blob, &chars, &labels)
    }

    /// Transcribe `word`, space-joined -- the CLI's output format.
    pub fn phonemize_str(&self, word: &str) -> String {
        self.phonemize(word).join(" ")
    }

    /// Transcribe a run of text: whitespace separates words, one transcription
    /// per word, in order. This is the batch entry point -- a whole sentence,
    /// a whole line, a whole file -- and it is deliberately not a "sentence"
    /// API: no punctuation model, no sandhi, just many words at once.
    pub fn phonemize_words(&self, text: &str) -> Vec<Vec<String>> {
        text.split_whitespace().map(|word| self.phonemize(word)).collect()
    }

    /// [`G2P::phonemize_words`], one transcription per line.
    pub fn phonemize_text(&self, text: &str) -> String {
        self.phonemize_words(text)
            .iter()
            .map(|phones| phones.join(" "))
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// Why a word was answered the way it was: `Some(reason)` when the
    /// exception path handled it, `None` when the model did.
    pub fn explain(&self, word: &str) -> Option<&'static str> {
        self.exceptions.reason(&text::normalize(word))
    }
}
